### ISSUE TITLE
This a fake?

### ISSUE THREAD

**Issue by ghost** [apurbajnu/Custom-Metabox#1]
This class is a fake and does absolutely nothing. Thank you for wasting my time.

**Comment by apurbajnu** [comment]
Have you read the documentation? You should also read the[ article ](https://www.apurba.me/custom-metabox-documentation/) . I have written this code for Developer not end user please remember. Can you share your code with me?

**Comment by ghost** [comment]
Yes i read but not work. Its a problem of javascript.

**Comment by apurbajnu** [comment]
May you share the code or some details with me? I have used this codebase more than 10 project.

**Comment by apurbajnu** [comment]
One more thing I haven't added Gutenberg support for this library. Please remember. This one will only work for Classic Editor.

**Comment by ghost** [comment]
The fields do not work (in the sense that they are not activated). The button in repeater field they are not clickable and the firefox and chrome inspector give an error to the meta.js file.

More honestly I do not know. I lost an afternoon for nothing and at the end I even turned my balls.

See a little you. If you work in your 10 projects I'm happy but it's not that I'm interested anymore.

**Comment by ghost** [comment]
I forgot. Change the link to the documentation because it leads to a blank page.

**Comment by apurbajnu** [comment]
I don't think you have enough experience.  I have mentioned clearly in my documentation that this script for developers only not for end users. Moreover that you are not able to share the issue. However thanks for your time. I am going to close the issue.

**Comment by ghost** [comment]
The one without experience is definitely you and you can also see from the spaghetti code you write.

Just to reiterate the concept you can always explain how I can have activated the library without building around something like a plugin or include it in a basic theme.

You know genius I am 48 years old and I write pc programs since the mid 80s of last century. I do not think it's yours that can give me lessons.

In any case, the fact that it does not work, has problems with javascript, css or other things are certainly not my problems. I try something that could help me and if it works ok, otherwise I'll go further. The rest is all your problem.

If you burn your ass because you have been told that your class does not work arranged. I only hope that the famous 10 projects on which you use this class are a little better than your site which also has broken links.
